### ISSUE TITLE
MetaController => AccessControl

### ISSUE THREAD

**Issue by lav45** [aquy/yii2-seo#1]
https://github.com/aquy/yii2-seo/blob/master/module/controllers/MetaController.php#L27-L30

Какое отношение к этому контроллеру имеют данные действия, если они тут даже не присутствуют.
По моему, это блок тут явно лишний.

**Comment by aquy** [comment]
Данные действия позволяют не залогиневшегося пользователя переадресовать на страницу входа и при ошибке действовать аналогичным образом.

Не уверен что это верный подход, но в моем приложении это оказалось решением.

**Comment by lav45** [comment]
### backend/config/main.php

``` php
return [
    'as access' => [
        'class' => 'yii\filters\AccessControl',
        'rules' => [
            [
                'actions' => ['login', 'error'],
                'allow' => true,
            ],
            [
                'roles' => ['@'],
                'allow' => true,
            ],
        ],
    ],
];
```

и тогда все страницы которые отображаются в админке будут доступны только для авторизованных пользователей кроме `'actions' => ['login', 'error'],`

**Comment by aquy** [comment]
поправил https://github.com/aquy/yii2-seo/commit/1c0de0d4f0a2a7106710d5912c0db0b2cc1dd6d4
